version: '3.9'

services:

  kong-database:
    image: postgres:alpine
    container_name: kong-database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=abcdefg123456
    volumes:
      - "db-data-kong-postgres:/var/lib/postgresql/data"
      - "/etc/localtime:/etc/localtime:ro"

  kong-migrations:
    image: kong:3.1.1-alpine
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_PASSWORD=abcdefg123456
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
    command: kong migrations bootstrap
    restart: on-failure
    depends_on:
      - kong-database

  kong:
    image: kong:3.1.1-alpine
    container_name: kong
    environment:
      - LC_CTYPE=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=abcdefg123456
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    restart: on-failure
    ports:
      - 80:8000
      - 8001:8001
    depends_on:
      - kong-migrations
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
  mock_api:
    image: python:3.10-alpine
    container_name: mock_api
    working_dir: /user/src
    command: sh -c "pip install fastapi uvicorn && uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./mock_api.py:/user/src/main.py
    expose:
      - 8000
    environment:
      - name=test


volumes:
 db-data-kong-postgres:
